Rscript -e 'install.packages("tm", repos = "http://cran.us.r-project.org")'
Rscript -e 'install.packages("SnowballC", repos = "http://cran.us.r-project.org”)'
Rscript -e 'install.packages("RColorBrewer", repos = "http://cran.us.r-project.org”)'
Rscript -e 'install.packages("XML", repos = "http://cran.us.r-project.org")'
Rscript -e 'install.packages("argparse", repos = "http://cran.us.r-project.org")'
Rscript -e 'install.packages("wordcloud", repos = "http://cran.us.r-project.org")'
